name: Python CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #step1: check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2
      #step2: set up python environment
      - name: Set up python 
        uses: actions/checkout@v2
        with:
          python-version: '3.8'
      # step 3: install dependecies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # step4: Run tests
      - name: Run tests
        run: pytest
